---
# tasks file for kernelupgrade

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install the nginx rpm from a remote repo
  yum:
    name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: present

- name: Install package with multiple repos enabled
  yum:
    name: kernel-ml
    enablerepo: "elrepo-kernel"

- name: update grub
  lineinfile:
    dest: "/etc/default/grub"
    regexp: "^GRUB_DEFAULT=0"
    line: "GRUB_DEFAULT=0"
  notify: "make grub config"
